site_name: Manual de uso da API de Avaliação e Acompanhamento
# Configuration
theme:
  locale: pt_BR
  name: material
  palette:
    primary: indigo
  favicon: img/logoGovBr.png
  logo: img/logoGovBr.png
  features:
    - navigation.instant  